services:
  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8080:8080
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - CASC_JENKINS_CONFIG=/var/jenkins_config/jenkins.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins/jenkins.yaml:/var/jenkins_config/jenkins.yaml:ro
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ./android-app:/workspace/android-app:ro
    networks:
      - jenkins

  docker:
    image: docker:dind
    ports:
      - 2376:2376
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_home:/var/jenkins_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jenkins

volumes:
  jenkins_home:
  jenkins-docker-certs:

networks:
  jenkins:
    driver: bridge
